// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Keep relative `file:./...` for migrate on Windows.
    // For Studio use: npm run db:studio
    url: process.env["DATABASE_URL"],
  },
});
